[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
prime_factorization = "1.0.5"

[dev-dependencies]
criterion = { version = "0.8.0", features = ["html_reports"] }

[[bench]]
name="benchmarks"
harness=false
